### PR TITLE
fixed code smells + pep8

### PR DESCRIPTION
**Pull request by phishontop**
- check the code works beforehand before accepting
- the file doesn't need closing when you use with open since it already handles this
- you don't know else statements when all you do is pass
- reduced the codebase by 20 lines
- made some functions only run once (since they don't need to run multiple times)

### CODE REVIEW

**Comment by Blank-c** [comment]
closing the file flushes the buffer (if its has some data). So you must not leave the file open.

**Comment by Smug246** [comment]
ye ill implement some of this but some bits are a bit bugged

**Comment by phishontop** [comment]
> closing the file flushes the buffer (if its has some data). So you must not leave the file open otherwise can result in data loss.

you might wanna read up on this, python handles the closing of the file when you use with open file as file:
https://stackoverflow.com/questions/34429519/python-difference-between-open-and-with-open

**Comment by Blank-c** [comment]
Oh, I didn't see the `with open()`, I thought you were talking about `open()`. My bad.

**Pull request closed without merging**
