### PR TITLE
please do it that it doesn't show my shit to my friends on stream, thanks

### PR DESCRIPTION
**Pull request by schwungvoll**
please do it that it doesn't show my shit to my friends on stream, thanks

### CODE REVIEW

**Comment by Smug246** [comment]
just because you want it doesn't mean everyone wants it. it's not hard to do it yourself. so no. not pushing this request

**Comment by schwungvoll** [comment]
dude everyone needs this

**Comment by schwungvoll** [comment]
nigga

**Comment by Smug246** [comment]
no

**Pull request closed without merging**
