### PR TITLE
Update setup.bat

### PR DESCRIPTION
**Pull request by KDot227**
batched

### CODE REVIEW

**Comment by KDot227** [comment]
Bro ignored me

**Comment by Smug246** [comment]
bro ur shi dont work i just tested it

**Comment by KDot227** [comment]
> bro ur shi dont work i just tested it

U gotta be dumb asf then

**Comment by KDot227** [comment]
Send error stg ik u a tard

**Comment by Smug246** [comment]
test it urself. it doesnt work idiot. 
image
prints that then closes

**Pull request closed without merging**
